### ISSUE TITLE
Write Tech Spec for AI Copilot

### ISSUE THREAD

**Issue by AGI-CEO** [mcsp-blue-ocean/quest-copilot#1]
I finished the AI Copilot Tech spec for review and consideration here ([https://docs.google.com/document/d/1yTvl-FqAYmKN8t8oxfK_DVOrzOgab7cT3ZbOKE6rYjs/edit?usp=sharing)
](https://docs.google.com/document/d/1yTvl-FqAYmKN8t8oxfK_DVOrzOgab7cT3ZbOKE6rYjs/edit?usp=sharing)
I included initial user story drafts to serve as a starting point.

LlamaIndex's js library is entirely typescript. To prevent typescript validation / linting errors for the entire quest repo, I recommend the backend for the AI chatbot to be a seperate repo which will be deployed and accessed by our main frontend as a microservice-style feature.

**Comment by AGI-CEO** [comment]
Pending review, questions, concerns, comments from team.

Stakeholders are api, server, database development teams.

**Comment by kajiwara12** [comment]
looked over the google doc, and everything seems good to me and seems like a good plan. I personally do not know a ton about some of the core components but I am willing to learn and help where you need me
